
<Snakepart>:
    size: 40, 40
    canvas.before:
        Color:
            rgb: 192, 192, 192
        Rectangle:
            size: self.size
            pos: self.pos

GameScreen:
    Widget:
        size: 40, 40
        pos: 120, 120
        id: food
        canvas.before:
            Color:
                rgb: 192, 192, 192
            Rectangle:
                size: self.size
                pos: self.pos
